spring:
  profiles:
    active: local

  session:
    redis:
      namespace: manibogo

  messages:
    basename: messages,ValidationMessages
    encoding: UTF-8

  data:
    web:
      pageable:
        max-page-size: 50
  jpa:
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/manibogo_oms_v2
    username: root
    password: 3520

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    kr.tatine.manibogo_oms_v2: debug

security:
  remember-me:
    key: uGfR1cWlEUy&Qi
    ttl: 1209600 # 14d
---
spring:
  config:
    activate:
      on-profile: prod

  flyway:
    enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(AP556YlhNzQtQdAGHbIrP9VZjlxGr85saviW4zTt4j8ijrXLSe0qnbhAM52jt3YuLcBQZuIbxq49rLvxfRzl49RbNEhF8AtLXz6ptpoPloM+IUP0L698QkCsiRx1Xui9hm5HQ2ZYe/ak98SiuAawB7aQIR9w//a6EoPMdao2v2k=)
    username: ENC(hyDirMnvkTOuZy1fCgg0inStRABuDatKtTQmw8kHw9kDRceCECAzMooOAtmN2rdw)
    password: ENC(RGsbi5/4Iqmly9DoUeMdgXNGNQzdScQciFWaMuIa7aEtUravs/TRP2wZhwg+Sl8z)

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      url: ENC(0Zxi8lSQDYl+OjVkiN05To7N5nwp9xzDe/oqE5DmPNbf3kFHS4exyoURC57G4bSVbkxNLk6LuTSNK8JZlA5NTFJgqMW/hqle6DUFzx9L4mSbI8fKj6x3yJ65tAPcePHT3+1et3zd1Bhd2kIH0ekz2A==)

security:
  remember-me:
    key: ENC(1iM0Jgz9hzhPqSpqhDXaJe2Wk9bvHjHFajFkaeJ8qOQwFsUpV2u8GJMSaUoOYsoj)
    ttl: 1209600 # 14d
