spring:
  profiles:
    active: local

  messages:
    basename: messages,ValidationMessages
    encoding: UTF-8

  data:
    web:
      pageable:
        max-page-size: 50
  jpa:
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/manibogo_oms_v2
    username: root
    password: 3520

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    kr.tatine.manibogo_oms_v2: debug