spring:
  profiles:
    active: local

  session:
    redis:
      namespace: manibogo

  messages:
    basename: messages,ValidationMessages
    encoding: UTF-8

  data:
    web:
      pageable:
        max-page-size: 50
  jpa:
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/manibogo_oms_v2
    username: root
    password: 3520

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    kr.tatine.manibogo_oms_v2: debug

security:
  remember-me:
    key: uGfR1cWlEUy&Qi
    ttl: 1209600 # 14d
---
spring:
  config:
    activate:
      on-profile: prod

  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/manibogo_v2_test
    username: root
    password: 3520

  jpa:
    hibernate:
      ddl-auto: validate

security:
  remember-me:
    key: uGfR1cWlEUy&Qi
    ttl: 1209600 # 14d