version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user
    overwrite: yes

hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/backup_jar.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root