version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user
    overwrite: yes

hooks:
  ApplicationStop:
    - location: stop_service.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: backup_jar.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: restart_service.sh
      timeout: 300
      runas: root